### ISSUE TITLE
I18n support

### ISSUE THREAD

**Issue by w568w** [TheArtyomMDev/BeWell#2]
Hi there,

I have just discovered your app on [lzzyOnDroid](https://apt.izzysoft.de/fdroid/index/apk/com.bewell), and I found that it provided much richer information than an average heart rate monitor app did. It is really nice to know that it is open source, too!

However, it seems that the app is using Russian as its default language, no English or any localization support else. Maybe I can help add some translations, like English or Chinese? Thanks in advance.

**Comment by TheArtyomMDev** [comment]
Hi, I'm planning to add localization a bit later (in next version probably). However u can help me with translation on Chinese (coz I don't know it, only English). 
It's nice to see that you are appreciating my work

**Comment by w568w** [comment]
> Hi, I'm planning to add localization a bit later (in next version probably).

That's great! I will keep an eye on this application for any new release.

**Comment by TheArtyomMDev** [comment]
Transaltion added
Login & signup added (to upload results on Firestore, I'm planning to make a measure history later)
