### ISSUE TITLE
Bluetooth support?

### ISSUE THREAD

**Issue by khimaros** [TheArtyomMDev/BeWell#7]
recent phones (eg. Pixel 6) place the flash father from the camera sensor and pulse is no longer detected.

it would be great to support Bluetooth LE sensors such as the Polar H7.

**Comment by TheArtyomMDev** [comment]
Hi, thanks for suggesting an enhancment! But this app was made generally to give ability to perform fast heart analysis via HRV method, so I'm not planning to add it. However, as far as I know there are already apps in Google Play that support bluetooth sensors

**Comment by khimaros** [comment]
none of the (open source) Bluetooth apps calculate HRV, and unfortunately newer devices don't position the flashlight in a way that is compatible with the light method.
